import { createFileRoute } from "@tanstack/react-router";
import { AppShell, PageHeader } from "@/components/AppShell";
import { Download, FileBarChart, FileText } from "lucide-react";

export const Route = createFileRoute("/reports")({
  component: Reports,
});

const reports = [
  { name: "Monthly Wealth Statement — November 2025", type: "Statement", date: "01 Dec 2025", size: "1.2 MB" },
  { name: "Portfolio Rebalance Advisory Q4 2025", type: "Advisory", date: "28 Nov 2025", size: "820 KB" },
  { name: "Tax Optimization Playbook FY 25-26", type: "Tax", date: "20 Nov 2025", size: "1.6 MB" },
  { name: "Goal Health Report — Household", type: "Goals", date: "15 Nov 2025", size: "640 KB" },
  { name: "Risk Profile Reassessment", type: "Risk", date: "01 Nov 2025", size: "410 KB" },
  { name: "Spending Behaviour Deep-Dive Q3", type: "Insights", date: "05 Oct 2025", size: "2.1 MB" },
];

function Reports() {
  return (
    <AppShell>
      <PageHeader title="Reports" subtitle="Personalized financial reports generated by AURA — audit-ready" right={
        <button className="inline-flex items-center gap-2 rounded-full gradient-brand px-4 py-2 text-sm font-semibold text-white shadow-elegant"><FileBarChart className="h-4 w-4" /> Generate custom report</button>
      } />

      <div className="rounded-2xl border border-border bg-card shadow-card">
        <ul className="divide-y divide-border">
          {reports.map((r) => (
            <li key={r.name} className="flex items-center gap-4 p-4">
              <div className="grid h-10 w-10 place-items-center rounded-lg bg-brand-soft text-primary"><FileText className="h-5 w-5" /></div>
              <div className="flex-1 min-w-0">
                <div className="truncate text-sm font-medium">{r.name}</div>
                <div className="mt-0.5 flex items-center gap-3 text-[11px] text-muted-foreground">
                  <span className="rounded-full border border-border bg-muted/40 px-2 py-0.5">{r.type}</span>
                  <span>{r.date}</span>
                  <span>{r.size}</span>
                </div>
              </div>
              <button className="inline-flex items-center gap-2 rounded-full border border-border bg-card px-3 py-1.5 text-xs font-semibold hover:bg-brand-soft hover:text-primary">
                <Download className="h-3.5 w-3.5" /> Download
              </button>
            </li>
          ))}
        </ul>
      </div>
    </AppShell>
  );
}
